version: '3.8'
services:
  db1:
    image: mcr.microsoft.com/mssql/server
    container_name: UserService
    restart: always
    environment:
      SA_PASSWORD: StrongPassword123!
      ACCEPT_EULA: Y
      MSSQL_DATABASE: UserServiceDB
      MSSQL_USER: kutluaylav
      MSSQL_PASSWORD: kutilavoiser333444
    ports:
      - "1433:1433"
    volumes:
      - db_data1:/var/opt/mssql

  db2:
    image: mcr.microsoft.com/mssql/server
    container_name: ProductSystem
    restart: always
    environment:
      SA_PASSWORD: StrongPassword123!
      ACCEPT_EULA: Y
      MSSQL_DATABASE: ProductSystemDB
      MSSQL_USER: kutluaylav
      MSSQL_PASSWORD: kutilavoiser333444
    ports:
      - "1434:1433"
    volumes:
      - db_data2:/var/opt/mssql

volumes:
  db_data1:
  db_data2: