version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server
    container_name: CompanySalesKU
    restart: always
    environment:
      SA_PASSWORD: StrongPassword123!
      ACCEPT_EULA: Y
      MSSQL_DATABASE: CompanySalesDB
      MSSQL_USER: kutluaylav
      MSSQL_PASSWORD: kutilavoiser333444
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql

volumes:
  db_data: